# Generated by Django 4.2.1 on 2023-08-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="task.project",
            ),
        ),
    ]
